name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main  # Déclenchement sur push vers main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ftp-1871.camoo.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /home/camerg5784/licence
